version: '3'

services: 
  node:
    build: 
      context: ./
      dockerfile: ./Docker/node/Dockerfile
    volumes: 
      - ./:/app
      - node_modules_volume:/app/node_modules
    ports: 
      - '3000:3000'

volumes: 
  node_modules_volume: